<a href="https://colab.research.google.com/github/shahabas123/Pneumonia-Detection-using-Chest-X-ray-Images/blob/main/CNN_ChestX_ray_kaggle_9_3_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
from skimage.io import imread
from skimage.transform import resize
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from keras.models import Sequential
import numpy as np
from sklearn.metrics import classification_report
import random

In [2]:
!pip install opendatasets

In [3]:
import opendatasets as od
od.download('https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: shahabasali08
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia


100%|██████████| 2.29G/2.29G [01:45<00:00, 23.3MB/s]


Taking training data path and resize

In [4]:
train_path='/content/chest-xray-pneumonia/chest_xray/train'
categories=['NORMAL','PNEUMONIA']
X_train=[]
y_train=[]
for category in categories:
  folder_path=os.path.join(train_path,category)
  images=os.listdir(folder_path)
  for img in images:
    img_path=os.path.join(folder_path,img)
    img_array=imread(img_path)
    img=resize(img_array,(150,150,1))
    X_train.append(img)
    y_train.append(categories.index(category))
  print("Loaded category:",category)

Loaded category: NORMAL
Loaded category: PNEUMONIA


taking test data path

In [5]:
test_path='/content/chest-xray-pneumonia/chest_xray/test'
categories=['NORMAL','PNEUMONIA']
X_test=[]
y_test=[]
for category in categories:
  folder_path=os.path.join(test_path,category)
  images=os.listdir(folder_path)
  for img in images:
    img_path=os.path.join(folder_path,img)
    img_array=imread(img_path)
    img=resize(img_array,(150,150,1))
    X_test.append(img)
    y_test.append(categories.index(category))
  print("Loaded category:",category)

Loaded category: NORMAL
Loaded category: PNEUMONIA


In [6]:
X_train=np.array(X_train)
X_test=np.array(X_test)
y_train=np.array(y_train)
y_test=np.array(y_test)

In [7]:
X_train.shape,y_train.shape

((5216, 150, 150, 1), (5216,))

In [8]:
X_test.shape,y_test.shape

((624, 150, 150, 1), (624,))

In [9]:
#random.seed(42)

Model

In [10]:
model=Sequential()

model.add(Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(MaxPool2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu',padding='same'))
model.add(Conv2D(64,(3,3),activation='relu',padding='same'))
model.add(MaxPool2D(2,2))

model.add(Conv2D(128,(3,3),activation='relu',padding='same'))
model.add(Conv2D(128,(3,3),activation='relu',padding='same'))
model.add(MaxPool2D(2,2))

model.add(Conv2D(256,(3,3),activation='relu',padding='same'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(256,(3,3),activation='relu',padding='same'))
model.add(Conv2D(256,(3,3),activation='relu',padding='same'))
model.add(MaxPool2D(2,2))












model.add(Flatten())

model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(64,activation='relu'))


model.add(Dense(1,activation='sigmoid'))


In [11]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [12]:
model.fit(X_train,y_train,epochs=150,batch_size=16)

Epoch 1/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 24s 34ms/step - accuracy: 0.7442 - loss: 0.5873
Epoch 2/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.7616 - loss: 0.4637
Epoch 3/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - accuracy: 0.8500 - loss: 0.3185
Epoch 4/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 33ms/step - accuracy: 0.8939 - loss: 0.2522
Epoch 5/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9348 - loss: 0.1714
Epoch 6/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9604 - loss: 0.1021
Epoch 7/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 34ms/step - accuracy: 0.9678 - loss: 0.0930
Epoch 8/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 35ms/step - accuracy: 0.9654 - loss: 0.0977
Epoch 9/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 35ms/step - accuracy: 0.9815 - loss: 0.0524
Epoch 10/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 11s 35ms/step - accuracy: 0.9831 - loss: 0.0519
Epoch 11/150
326/326 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - accuracy: 0.9835 - loss: 0.0471
Epoch 12/150
326/32

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (16, 150, 150, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (16, 150, 150, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (16, 75, 75, 32)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (16, 75, 75, 64)            │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (16, 75, 75, 64)            │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (16, 37, 37, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (16, 37, 37, 128)           │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (16, 37, 37, 128)           │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (16, 18, 18, 128)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (16, 18, 18, 256)           │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (16, 9, 9, 256)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (16, 9, 9, 256)             │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (16, 9, 9, 256)             │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (16, 4, 4, 256)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (16, 4096)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (16, 256)                   │       1,048,832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (16, 128)                   │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (16, 128)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (16, 64)                    │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (16, 1)                     │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 8,555,429 (32.64 MB)

 Trainable params: 2,851,809 (10.88 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,703,620 (21.76 MB)

Evaluating and predicting

In [14]:
model.evaluate(X_test,y_test)

20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.5769 - loss: 25.7870


[13.355522155761719, 0.7660256624221802]

In [15]:
y_pred=model.predict(X_test)
y_pred

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step


array([[1.00000000e+00],
       [9.08026397e-02],
       [1.93640375e-07],
       [6.97151625e-09],
       [9.93535817e-01],
       [2.80372769e-09],
       [1.00000000e+00],
       [4.75950742e-07],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.01001170e-02],
       [1.00000000e+00],
       [1.70653491e-09],
       [1.18468106e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [2.55884469e-08],
       [1.00000000e+00],
       [9.39324746e-05],
       [1.07962592e-07],
       [7.45719135e-01],
       [6.31954390e-05],
       [1.00000000e+00],
       [7.81390300e-11],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [6.77604810e-04],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [8.89095128e-01],
       [1.00000000e+00],
       [3.72568309e-07],


In [16]:
y_pred1=(y_pred>0.5).astype(int)
y_pred1

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
    

In [17]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [18]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.94      0.40      0.56       234
           1       0.73      0.98      0.84       390

    accuracy                           0.77       624
   macro avg       0.84      0.69      0.70       624
weighted avg       0.81      0.77      0.74       624



New image testing

In [19]:
def pred_new(new_img,model):
  resized_img=resize(new_img,(150,150,1))
  img=resized_img.reshape(1,150,150,1)
  pred=model.predict(img)
  ind = int(pred[0] > 0.5)
  categories=['NORMAL','PNEUMONIA']
  print(categories[ind])

In [20]:
img_path=input("enter image path:")
new_img=imread(img_path)
pred_new(new_img,model)

enter image path:/content/chest-xray-pneumonia/chest_xray/test/PNEUMONIA/person100_bacteria_478.jpeg
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
PNEUMONIA


<ipython-input-19-588bcd7be4f6>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  ind = int(pred[0] > 0.5)


In [21]:
model.save("pneumonia_model.h5")